### ISSUE TITLE
Why Turnabout mess with Animate dead Spell

### ISSUE THREAD

**Issue by TotoR115** [Pocket-Plane-Group/Turnabout#1]
Oddly, Turnabout changes the creature summoned by "animate dead" spells (ghastsu.cre):
https://github.com/Pocket-Plane-Group/Turnabout/blob/12392a821bdd4f6668ee667e7f3a3acfd1648559/turnabout/setup-turnabout.tp2#L158

It has nothing to do with this mod and should be removed. In addition, it is not documented.

**Comment by Gitjas** [comment]
I'm all for removing tweaks that have nothing to do with the scope of the mod, but I'd need more elaboration before removing something I don't understand (because I don't know my way around what this does and why the author thought it might be useful; to be honest I don't know what it does at all.)

**Comment by TotoR115** [comment]
I'm afraid that I don't understand myself, it seems coming from nowhere. 

for comparisons of what this change does, see:

https://drive.google.com/file/d/1pMIBHaVvYhqENyBfibrAv7eYrhaZygb3/view?usp=sharing
https://drive.google.com/file/d/1GDSgfCUJ5dQCnj5mIJyQaqkgUAVnpxAu/view?usp=sharing
https://drive.google.com/file/d/1NBwHy_3kfkx9RKA9uy7REp--Iv6Edsv2/view?usp=sharing

It is a raw copy in the tp2, but you'r right, it could need more investigation that I won't be able to do in short term (maybe never).

It is, however, odd to make a modification of a summon without warning... For me, there is no apparent reason for this modification, it looks more like a UB tweak, left by mistake...

**Comment by CamDawg** [comment]
Yeah, there's a bug here, but it's a little more subtle. Tiax's special Summon Ghast ability in oBG is summoning ghasts.cre, which he does via spin115.spl. This creature was exclusive to Tiax's ability. 

spin115.spl was carried over into oBG2 and, though spin115 is unused, was changed to summon ghastsu.cre instead. At the same time, the Animate Dead spells also use ghastsu.cre (via spandead.eff). Despite the name, ghastsu.cre is a skeleton. 

With the ghastsu.cre copy, Tiax's special ability works as it should, but now Animate Dead spells are creating Tiax's special ghast instead of skeletons. Without the copy, Tiax's Summon Ghast ability summons an inferior skeleton. 

What we need to do is to keep the ghastsu.cre copy, but rename the destination file when adding it to the game and patch spin115.spl to point to the new creature file. The new Tiax in the mod already has spin115.spl known and memorized.

**Comment by CamDawg** [comment]
Pull request filed.

**Comment by TotoR115** [comment]
Ouch, I would have never found this one...

BGT change spin115.spl resource for 'ghasts.cre', that explain why I haven't found any other spell that use 'ghastsu.cre...

Thank you for the explanation  👍

**Comment by TotoR115** [comment]
Second thought: As it is already modified with BGT, spin115.spl should not be updated in this case...

**Comment by CamDawg** [comment]
Closing this; fixed in PR https://github.com/Pocket-Plane-Group/Turnabout/pull/2
